# -*- coding: utf-8 -*-
"""RAG_Agent_Knowledge_Sourrce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mWsOTDEOBtI031Oaj1Uvg8kHpcReWIMR

# 🤗 RAG Pipeline — HuggingFace + Multi-Document Support
> Supports **PDF**, **Excel (.xlsx)**, and **Word (.docx)** uploads  
> Uses **HuggingFace** Embeddings + Inference API (replaces OpenAI)

### RAG Flow
```
Upload Docs → Split → Embed (HF) → FAISS Store → Retrieve → Augment → Generate (HF LLM)
```

## 🔑 Step 0 — Set HuggingFace API Key
"""

import os

# ✅ Replace with your OpenRouter API key
# Get it from: https://openrouter.ai/keys
os.environ["OPENROUTER_API_KEY"] = "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"

print("✅ OpenRouter API key set!")

"""## 📦 Install Libraries"""

!pip install -q \
    langchain \
    langchain-community \
    langchain-huggingface \
    faiss-cpu \
    sentence-transformers \
    huggingface-hub \
    pypdf \
    openpyxl \
    python-docx \
    python-dotenv

print("✅ All libraries installed!")

from langchain_text_splitters import RecursiveCharacterTextSplitter

pip install --upgrade langchain langchain-text-splitters langchain-community

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.llms import HuggingFaceEndpoint


# Rest of your code



"""## 📥 Imports"""

import os
import tempfile
import pandas as pd

# Text Splitter
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Document
from langchain_core.documents import Document

# Embeddings and LLM
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.llms import HuggingFaceEndpoint

# Vector Store
from langchain_community.vectorstores import FAISS

# Prompts and Runnables
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

# Document Loaders
from langchain_community.document_loaders import PyPDFLoader, Docx2txtLoader

print("✅ Imports done!")

"""## 📂 Step 1a — Document Ingestion
> Upload your **PDF**, **Excel**, or **Word** files here.  
> In Google Colab: use the 📁 sidebar to upload, then provide the file path below.
"""

# ─────────────────────────────────────────────────────────────
# 📌 CONFIGURE: Add your file paths here
# In Colab: upload files via the Files panel (left sidebar)
# Then update the paths below
# ─────────────────────────────────────────────────────────────

FILE_PATHS = [

     "/content/AI ENgineering Nootbook.pdf",
    # "sample.xlsx",
    # "sample.docx",
]

# ─────────────────────────────────────────────────────────────
# Document loader — handles PDF, Excel, Word automatically
# ─────────────────────────────────────────────────────────────

def load_documents(file_paths: list) -> list:
    """Load PDF, Excel (.xlsx), and Word (.docx) files into LangChain Documents."""
    all_docs = []

    for path in file_paths:
        ext = os.path.splitext(path)[-1].lower()
        print(f"📄 Loading: {path}  [{ext}]")

        if ext == ".pdf":
            loader = PyPDFLoader(path)
            docs = loader.load()
            all_docs.extend(docs)
            print(f"   ✅ Loaded {len(docs)} pages from PDF")

        elif ext in [".xlsx", ".xls"]:
            # Read all sheets
            xls = pd.read_excel(path, sheet_name=None)
            for sheet_name, df in xls.items():
                text = f"Sheet: {sheet_name}\n" + df.to_string(index=False)
                doc = Document(
                    page_content=text,
                    metadata={"source": path, "sheet": sheet_name}
                )
                all_docs.append(doc)
            print(f"   ✅ Loaded {len(xls)} sheet(s) from Excel")

        elif ext == ".docx":
            loader = Docx2txtLoader(path)
            docs = loader.load()
            all_docs.extend(docs)
            print(f"   ✅ Loaded {len(docs)} section(s) from Word")

        else:
            print(f"   ⚠️  Unsupported format: {ext} — skipping")

    print(f"\n📦 Total documents loaded: {len(all_docs)}")
    return all_docs


raw_docs = load_documents(FILE_PATHS)

# Preview first doc
if raw_docs:
    print("\n--- Preview of first document ---")
    print(raw_docs[0].page_content[:500])
    print("Metadata:", raw_docs[0].metadata)
else:
    print("⚠️  No files loaded. Add file paths to FILE_PATHS above and re-run.")



"""## ✂️ Step 1b — Text Splitting"""

splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

chunks = splitter.split_documents(raw_docs)

print(f"✅ Total chunks created: {len(chunks)}")

# Preview a chunk
if chunks:
    print("\n--- Sample Chunk ---")
    print(chunks[0].page_content)
    print("Metadata:", chunks[0].metadata)

"""## 🔢 Step 1c & 1d — Embedding + Vector Store
> Using **`sentence-transformers/all-MiniLM-L6-v2`** — free, runs locally, no API key needed for embeddings.
"""

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# Use a free embedding model
embedding_model_name = "BAAI/bge-small-en-v1.5"  # or any other free model

print("⏳ Loading embedding model (downloads once)...")

embeddings = HuggingFaceEmbeddings(
    model_name=embedding_model_name,
    model_kwargs={"device": "cpu"},  # Use "cuda" if GPU is available
    encode_kwargs={"normalize_embeddings": True}
)

print("✅ Embedding model loaded!")

# Build FAISS vector store
print("⏳ Building FAISS vector store...")
vector_store = FAISS.from_documents(chunks, embeddings)
print(f"✅ Vector store built! Total vectors: {vector_store.index.ntotal}")

# Optional: Save and reload vector store (useful for large docs)
# vector_store.save_local("faiss_index")
# vector_store = FAISS.load_local("faiss_index", embeddings, allow_dangerous_deserialization=True)
print("Vector store ready. Uncomment above lines to persist to disk.")

"""## 🔍 Step 2 — Retriever"""

retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 4}   # retrieve top-4 most relevant chunks
)

print("✅ Retriever ready!")
print(retriever)

# 🧪 Test the retriever
test_query = "What is this document about?"
test_results = retriever.invoke(test_query)

print(f"Query: '{test_query}'")
print(f"Retrieved {len(test_results)} chunks:\n")
for i, doc in enumerate(test_results):
    print(f"[{i+1}] Source: {doc.metadata.get('source', 'N/A')} | Page: {doc.metadata.get('page', 'N/A')}")
    print(doc.page_content[:300])
    print("---")

"""## 🤗 Step 3 — Augmentation (HuggingFace LLM)
> Using **Mistral-7B-Instruct** via HuggingFace Inference API (free tier).  
> You can swap `repo_id` with any other supported model.
"""

!pip install langchain-openai

!pip show langchain-openai



# ✅ Remove any HuggingFaceEndpoint — use this instead
from langchain_openai import ChatOpenAI
import os

os.environ["OPENROUTER_API_KEY"] = "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"

llm = ChatOpenAI(
    model="meta-llama/llama-3.3-70b-instruct",
    temperature=0.2,
    max_tokens=512,
    base_url="https://openrouter.ai/api/v1",
    api_key=os.environ["OPENROUTER_API_KEY"],
)

print("✅ LLM ready!")

# Quick test
response = llm.invoke("Say hello in one sentence.")
print(response.content)

!pip install -q langchain==0.3.25 langchain-core==0.3.58 langchain-community==0.3.24 langchain-openai langchain-huggingface==0.1.2 langchain-text-splitters==0.3.8 faiss-cpu sentence-transformers pypdf openpyxl python-docx docx2txt

prompt = PromptTemplate(
    template="""<s>[INST]
You are a helpful assistant. Answer the question using ONLY the context provided below.
If the answer is not in the context, say "I don't have enough information in the provided documents."
Be concise and clear.

Context:
{context}

Question: {question}
[/INST]""",
    input_variables=["context", "question"]
)

print("✅ Prompt template ready!")

"""## 🔗 Step 4 — Full RAG Chain"""

from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def format_docs(retrieved_docs):
    """Combine retrieved chunks into a single context string with source info."""
    parts = []
    for i, doc in enumerate(retrieved_docs):
        source = doc.metadata.get("source", "unknown")
        page   = doc.metadata.get("page",   "")
        sheet  = doc.metadata.get("sheet",  "")
        label  = f"[Doc {i+1} | {os.path.basename(source)}"
        if page: label += f" | Page {page}"
        if sheet: label += f" | Sheet: {sheet}"
        label += "]"
        parts.append(f"{label}\n{doc.page_content}")
    return "\n\n".join(parts)

parser = StrOutputParser()

parallel_chain = RunnableParallel({
    "context":  retriever | RunnableLambda(format_docs),
    "question": RunnablePassthrough()
})

main_chain = parallel_chain | prompt | llm | parser

print("✅ RAG chain ready!")

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough

# Define your prompt template
prompt = ChatPromptTemplate.from_template(
    """
    Answer the question based on the following context:
    {context}

    Question: {question}
    """
)

# Define your main chain
main_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

from langchain_core.prompts import ChatPromptTemplate

# ─────────────────────────────────────────────────────────────
# Option 1 — Direct question (no RAG, just LLM)
# ─────────────────────────────────────────────────────────────
response = llm.invoke("What is Overfitting ")
print(response.content)

"""## 💬 Ask Questions About Your Documents"""

# ─────────────────────────────────────────────────────────────
# 🔁 Interactive Q&A loop — keep asking questions!
# Type 'exit' to stop
# ─────────────────────────────────────────────────────────────

print("🤖 Interactive RAG Q&A")
print("Type your question below. Type 'exit' to stop.\n")

while True:
    user_input = input("You: ").strip()
    if user_input.lower() in ["exit", "quit", "q"]:
        print("👋 Exiting. Goodbye!")
        break
    if not user_input:
        continue
    print("⏳ Thinking...")
    response = main_chain.invoke(user_input)
    print(f"\n🤖 Answer: {response}\n")
    print("-" * 60)

"""---
## 📋 Quick Reference

| Component | Old (OpenAI) | New (HuggingFace) |
|---|---|---|
| API Key | `OPENAI_API_KEY` | `HUGGINGFACEHUB_API_TOKEN` |
| Embeddings | `OpenAIEmbeddings` | `HuggingFaceEmbeddings` |
| LLM | `ChatOpenAI (gpt-4o-mini)` | `HuggingFaceEndpoint (Mistral-7B)` |
| Vector Store | FAISS | FAISS (unchanged) |
| Document Input | YouTube transcript only | PDF + Excel + Word |

### 🔁 To switch models, change `repo_id`:
```python
repo_id = "google/flan-t5-large"               # Lightweight
repo_id = "HuggingFaceH4/zephyr-7b-beta"       # Chat-optimized  
repo_id = "mistralai/Mistral-7B-Instruct-v0.2" # Best quality (default)
```

### 📁 Supported file types:
- `PDF` → `PyPDFLoader` — extracts text page-by-page
- `Excel (.xlsx)` → `pandas` — reads all sheets
- `Word (.docx)` → `Docx2txtLoader` — extracts all paragraphs
"""